All:hello strings keybd lib structs fileio

hello:
	gcc hello.c -o hello

strings:
	gcc strings.c -o strings

keybd:
	gcc keybd.c -o keybd

lib:
	gcc my_lib.c my_driver.c -o mylib

structs:
	gcc structs.c -o structs

fileio:
	gcc fileio.c -o fileio

clean:
	rm hello strings keybd mylib structs fileio
